title: "Nduka Amakihe"
description: "Personal website for Nduka Amakihe, an aerospace engineering undergraduate at Queen Mary University of London"
url: "https://ndukaamakihe.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
timezone: Europe/London

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
